version: '3.8'

services:
  mongodb:
    image: mongo:5.0
    container_name: chat-mongodb
    restart: always
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=chatuser
      - MONGO_INITDB_ROOT_PASSWORD=chatpassword
    networks:
      - chat-network

  api:
    build:
      context: ./packages/api
      dockerfile: Dockerfile
    container_name: chat-api
    restart: always
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - MONGO_URI=mongodb://chatuser:chatpassword@mongodb:27017/chatapp?authSource=admin
      - JWT_SECRET=tu_secreto_jwt_seguro
      - CORS_ORIGIN=http://localhost:3000
    depends_on:
      - mongodb
    networks:
      - chat-network

  web:
    build:
      context: ./packages/web
      dockerfile: Dockerfile
    container_name: chat-web
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - NEXT_PUBLIC_API_URL=http://localhost:3001
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=tu_secreto_nextauth_seguro
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
    depends_on:
      - api
    networks:
      - chat-network

networks:
  chat-network:
    driver: bridge

volumes:
  mongodb_data:
